from . import (
    base,
    base_partner_merge_automatic_wizard,
    ir_attachment,
    ir_cron,
    ir_model_data,
    ir_rule,
    ir_ui_menu,
    ir_ui_view,
    multicompany_config,
    multicompany_security,
    res_company,
    res_config_settings,
    res_partner,
    res_users,
    res_users_apikeys,
)
